### ISSUE TITLE
Fourth Issue

### ISSUE THREAD

**Issue by legalalexa** [legalalexa/self-project-1#5]
Fourth issue to be resolved

**Comment by charlesmike** [comment]
@legalalexa thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-20T15:35:49.093415``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-20T15:35:49). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-20T15:35:49). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@legalalexa I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
